export type Theme = 'light' | 'dark';

export type ThemeSetting = 'light' | 'dark' | 'system' | 'system-inverse';

export type DaisyUITheme = {
  colorScheme: Theme;
  variables: Record<string, string>;
};

/**
 * Check whether a theme follows the system appearance.
 *
 * @param setting - theme setting
 * @returns true if the theme follows the system appearance, false otherwise
 */
export function isSystemTheme(setting: ThemeSetting): setting is 'system' | 'system-inverse' {
  return setting === 'system' || setting === 'system-inverse';
}

/**
 * Resolve a theme setting to a concrete light or dark theme.
 *
 * @param setting - theme setting
 * @param prefersDark - whether the system prefers a dark appearance
 * @returns resolved light or dark theme
 */
export function resolveTheme(setting: ThemeSetting, prefersDark: boolean): Theme {
  if (setting === 'system') {
    return prefersDark ? 'dark' : 'light';
  }
  if (setting === 'system-inverse') {
    return prefersDark ? 'light' : 'dark';
  }
  return setting;
}

/**
 * Parse a theme generated by the daisyUI theme generator.
 *
 * @param css - daisyUI theme CSS
 * @returns parsed color scheme and theme variables
 */
export function parseDaisyUITheme(css: string): DaisyUITheme {
  const match = css.match(/^\s*@plugin\s+["']daisyui\/theme["']\s*\{([\s\S]*)\}\s*$/);
  if (!match || /[{}]/.test(match[1])) {
    throw new Error('Invalid daisyUI theme CSS');
  }

  let colorScheme: 'light' | 'dark' | undefined;
  let hasName = false;
  const variables: Record<string, string> = {};
  const declarations = match[1].replace(/\/\*[\s\S]*?\*\//g, '').split(';');

  for (const declaration of declarations) {
    const separator = declaration.indexOf(':');
    if (separator < 0) {
      continue;
    }
    const property = declaration.slice(0, separator).trim();
    const value = declaration.slice(separator + 1).trim();
    if (property === 'name' && value) {
      hasName = true;
    } else if (property === 'color-scheme') {
      colorScheme = value.match(/^(['"]?)(light|dark)\1$/)?.[2] as 'light' | 'dark' | undefined;
    } else if (property.startsWith('--')) {
      if (!/^--[a-zA-Z0-9_-]+$/.test(property) || !value) {
        throw new Error('Invalid daisyUI theme CSS');
      }
      variables[property] = value;
    }
  }

  if (!hasName || !colorScheme || Object.keys(variables).length === 0) {
    throw new Error('Invalid daisyUI theme CSS');
  }

  return { colorScheme, variables };
}

/**
 * Build runtime styles for configured custom themes.
 *
 * @param themes - custom light and dark theme CSS
 * @returns combined runtime CSS
 */
export function buildRuntimeStyles(themes: Record<Theme, string>): string {
  const styles: string[] = [];
  for (const theme of ['light', 'dark'] as const) {
    const css = themes[theme].trim();
    if (css) {
      const { colorScheme, variables } = parseDaisyUITheme(css);
      const declarations = [
        `  color-scheme: ${colorScheme};`,
        ...Object.entries(variables).map(([property, value]) => `  ${property}: ${value};`)
      ];
      styles.push([`[data-theme="${theme}"] {`, ...declarations, '}'].join('\n'));
    }
  }
  return styles.join('\n');
}
