name: Feature Request
description: Suggest an idea for this project
title: '[Feature Request]: '
body:
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to add?
      description: Please provide a clear and concise description of the feature you want to add.
      placeholder: I would like to add...
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why do you need this feature?
      description: Please explain why this feature is important and what problem it solves.
      placeholder: This feature would help me...
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context (optional)
      description: Add any other context, screenshots, or examples about the feature request here.
